### ISSUE TITLE
ws not support protocol in sockjs-client in browser

### ISSUE THREAD

**Issue by only-kuban** [antonioaguilar/ws-nats#2]
Hi, what is problem?

The URL's scheme must be either 'http:' or 'https:'. 'ws:' is not allowed.
    at new E (ws-nats.umd.js:8)
    at new s (ws-nats.umd.js:8)

**Comment by antonioaguilar** [comment]
@only-kuban because we are using SockJS websocket library, you need to use `http` or `https` in the websocket URL, e.g. nats.connect({url: 'https://my.websocketserver.com', ....). To connect to NATS server using `ws-nats`, you need to first connect to a Websocket to TCP proxy that will proxy client connections to the NATS server
